usda_api_key = "jbMrll1puv15lRsTelpixnTv9f6Ur5iXVzqWbQgi"
spoonacular_key = "e00b518d18b64fc2aba5fdfc6733f0cf"
pcloud_recipes_url = "https://... (твій публічний raw/csv лінк)"
pcloud_prices_url = "https://... (json з цінами)"
pcloud_prices_write_url = ""  # (опційно) посилання на POST/PUT API
