usda_api_key = "jbMrll1puv15lRsTelpixnTv9f6Ur5iXVzqWbQgi"
spoonacular_key = "e00b518d18b64fc2aba5fdfc6733f0cf"
pcloud_recipes_url = "https://e.pcloud.link/publink/show?code=XZjPT6Z52XOBDT44xVwAE03QJciY7GX2cuk"
pcloud_prices_url = "https://e.pcloud.link/publink/show?code=XZ4PT6ZuOaEcwXGgpyCCcDG0J1B4bDUmmRV"
pcloud_prices_write_url = ""  # (опційно) посилання на POST/PUT API
